/*
  ==============================================================================

    This file was auto-generated by the Jucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_C005C9A__
#define __PLUGINEDITOR_H_C005C9A__

#include "../JuceLibraryCode/JuceHeader.h"
#include "../JuceLibraryCode/JucePluginCharacteristics.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class BrocoliPlayerAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    BrocoliPlayerAudioProcessorEditor (BrocoliPlayerAudioProcessor* ownerFilter);
    ~BrocoliPlayerAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_C005C9A__
